#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := forward_comp
SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = forward_comp.py module_load.py

include $(MODULE_MAKEFILE)
